apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    - name: mysql-port
      containerPort: 3306
    env:
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: username
            key: username
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: password
            key: password
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rootPassword
            key: rootPassword
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: database
            key: database
